export enum LocalizationKey {
  WELCOME = "welcome",
  HOME = "home",
  START = "start",
  LOADING = "loading",
  SLOGAN = "Good Food, Great Vibes!",
  MORE = "Learn more",
  GO_HOME_NOW = "Skip to Home",
  ON1_QUOTE = "Identify Materials Easy",
  ON1_SUBQUOTE = `Quickly import all the ingredients \n in seconds \n Don't have to wait long!`,
  ON2_QUOTE = "Recommend Diverse Dishes",
  ON2_SUBQUOTE = `Quick Breakfast \n Nutritional Lunch \n Gathering Dinner \n Whatever you need, Flavorly has it all!`,
  ON3_QUOTE = "Flavorly Let's cook!",
  ON3_SUBQUOTE = `Choose your favorite recipe \n Flavorly is ready!`,
  NEXT = "Next",
}
